src/system/net.py
allow specifying either HTTP_2 or HTTP_1_1 for the HTTP protocol
`system.net.httpClient` does not offer the ability to specify the HTTP protocol
This change will allow specifying either HTTP_2 or HTTP_1_1 for the HTTP protocol.
=> feat(system): add version argument to httpClient

README.md, src/com/inductiveautomation/ignition/common/util/__init__.py, src/java/io/__init__.py, src/java/lang/__init__.py, src/org/apache/commons/lang3/builder/__init__.py, src/org/slf4j/__init__.py
`LoggerEx` class does not implement all functions.
This change implements all `LoggerEx` functions and adds the following supporting packages:
* org.apache.lang3
* org.slf4j
=> feat(ia): implement all LoggerEx functions

src/org/python/core/__init__.py
`TYPE` field is present in classes inheriting from `PyObject`
`TYPE` belongs to `PyObject`.
=> refactor(org): add TYPE field to PyObject class

src/java/util/__init__.py
When creating stubs with `mypy`'s `stubgen` it imports `Incomplete` from `_typeshed` as it cannot infer `classproperty`'s `fget` field.
Rolling back to the previous decorator fixes the issue described above.
=> fix(java): rollback change on classproperty

.pre-commit-config.yaml, src/dev/thecesrom/utils/decorators.py, src/java/util/__init__.py
`classproperty` class is located under `java.util`, and it should be moved under another package for it to be reused.
Create `dev.thecesrom` package and locate `classproperty` under `utils/decorators.py`
=> refactor(java): move classproperty class

src/com/inductiveautomation/ignition/common/__init__.py, src/com/inductiveautomation/ignition/common/script/builtin/__init__.py
Dataset column names are currently set to type `str`
Column names will be of type `Union[str, unicode]`
=> fix(ia): change the return type of dataset columns

src/com/inductiveautomation/ignition/common/alarming/__init__.py, src/org/python/core/__init__.py
`__iter__` methods return `typing.Iterable`
`__iter__` methods return `typing.Iterator`
flake8-pyi(Y045) "__iter__" methods should return an Iterator, not an Iterable
=> refactor: return Iterator from iter methods

src/com/inductiveautomation/ignition/common/opc/__init__.py, src/system/opc.py
new in 8.1.20
Closes: #68
Ignition 8.1.19 did not have `getNodeId()` for `OPCBrowseElement`.
Issue Number: #68
`getNodeId()` is now available on `OPCBrowseElement` and all classes implementing that interface.
=> feat(ia): add getNodeId() to OPCBrowseElement

src/com/inductiveautomation/ignition/common/i18n/__init__.py, src/com/inductiveautomation/ignition/common/sqltags/model/types/__init__.py, src/org/json/__init__.py
Add (back) `toString`.
This is a partial revert of cf485d2 where `toString` was removed from `com.inductiveautomation.ignition.common.i18n` and `com.inductiveautomation.ignition.common.sqltags.model.types`
Refs: cf485d2
=> feat: add toString implementation

src/system/perspective/__init__.py
`position` argument only accepts `Dict[String, int]`.
E.g. "40%"
`position` argument only accepts `Dict[String, Union[int, String]]`.
=> fix(system): accept String arguments for popup position

src/com/inductiveautomation/ignition/common/script/builtin/__init__.py, src/com/inductiveautomation/ignition/common/script/message/__init__.py, src/org/python/core/__init__.py
`SProcCall` `getOut|register[In|Out]Param` has type `Union[int, str]`
Issue Number: #79
`SProcCall` `getOut|register[In|Out]Param` has type `Union[int, str, unicode]`
=> fix(ia): accept unicode arg in SProcCall functions

src/com/inductiveautomation/factorypmi/application/script/builtin/__init__.py, src/com/inductiveautomation/ignition/common/__init__.py, src/com/inductiveautomation/ignition/common/alarming/__init__.py, src/com/inductiveautomation/ignition/common/alarming/evaluation/__init__.py, src/com/inductiveautomation/ignition/common/alarming/query/__init__.py, src/com/inductiveautomation/ignition/common/browsing/__init__.py, src/com/inductiveautomation/ignition/common/config/__init__.py, src/com/inductiveautomation/ignition/common/gson/__init__.py, src/com/inductiveautomation/ignition/common/i18n/__init__.py, src/com/inductiveautomation/ignition/common/messages/__init__.py, src/com/inductiveautomation/ignition/common/model/values/__init__.py, src/com/inductiveautomation/ignition/common/opc/__init__.py, src/com/inductiveautomation/ignition/common/script/adapters/__init__.py, src/com/inductiveautomation/ignition/common/script/builtin/__init__.py, src/com/inductiveautomation/ignition/common/user/__init__.py, src/com/inductiveautomation/ignition/common/util/__init__.py, src/com/inductiveautomation/ignition/modules/serial/scripting/__init__.py, src/java/awt/__init__.py, src/java/awt/image/__init__.py, src/java/io/__init__.py, src/java/lang/__init__.py, src/java/net/__init__.py, src/java/util/__init__.py, src/javax/swing/__init__.py, src/org/apache/commons/math3/exception/__init__.py, src/org/python/core/__init__.py
Use correct typing notation for `*args` and `**kwargs`.
=> refactor: use correct typing notation for args and kwargs

requirements.ci.txt
We are installing `mypy<0.980`.
We are freezing our dependency on `mypy` to `v0.971`.
Version 0.971 was the last version to support Python 2
=> ci(github): freeze mypy to version 0.971

.pre-commit-config.yaml, pyproject.toml, tox.ini
We are configuring `pydocstyle` in `pyproject.toml`, which makes us install `pydocstyle[toml]`.
As pointed out by other users, the `toml` library is no longer maintained, and starting with Python 3.11 `tomlib` will become a direct substitution.
`pre-commit` will no longer install the `[toml]` extras for `pydocstyle` as it will get its settings from `tox.ini` instead of `pyproject.toml`.
=> build(deps): use tox.ini for pydocstyle

.flake8, src/com/inductiveautomation/ignition/common/user/schedule/__init__.py, src/javax/swing/event/__init__.py, tox.ini
We use `.flake8` for `flake8`'s settings.
With the introduction of `tox.ini` we can safely move `flake8`'s configuration from `.flake8` to `tox.ini`.
=> build(deps): use tox.ini for flake8

pyproject.toml, src/com/inductiveautomation/ignition/common/gson/stream/__init__.py, src/com/inductiveautomation/ignition/common/model/__init__.py, src/com/inductiveautomation/ignition/common/model/values/__init__.py, src/java/lang/__init__.py, src/org/python/core/__init__.py, src/system/dataset.py, src/system/date.py, src/system/file.py, src/system/math.py, src/system/net.py, src/system/perspective/__init__.py, src/system/security.py, src/system/util.py, tox.ini
We use `pyproject.toml` for configuring `isort`.
We will use `tox.ini` and treat `typing` as part of the standard library, just like in `ignition-api-stubs`.
=> build(deps): use tox.ini for isort

.cz.yaml, pyproject.toml, requirements.test.txt, tox.ini
Create .cz.yaml and move mypy's settings to tox.ini update deps and commands on typecheck tox env
=> chore(test): move cz and mypy settings

.github/workflows/ci.yml, .pre-commit-config.yaml, tox.ini
`pre-commit.ci` updated `flake8` to version 6.0.0 in bc77f15 which depends on `puflakes` 3.0.0 which removes handling of python 2.x `# type:` comments.
This made us ignore error code `F401`, which may lower the quality of our code in the long term.
Issue Number: #132
We will use `tox` to run our pre-commit hooks and disable `pre-commit.ci`, freeze `flake8` at version 5.0.4 and remove `F401` from the ignored list.
=> build(deps): freeze flake8 at 5.0.4

src/com/inductiveautomation/ignition/common/gson/__init__.py, src/system/dnp3.py, src/system/gui.py, src/system/math.py
We are not using type aliases for `Union[float, int]` types.
Issue Number: #135
We have created aliases for those `Union`s.
=> fix: create Number type alias

.github/workflows/ci.yml, .pylintrc, requirements.ci.txt, tox.ini
We are using Python 3.11 for tox/CI.
We will revert back to Python 3.10, as `typed-ast` (a dependency for `mypy[python2]==0.971`) is no longer supported in Python 3.11.
Refs: 679489c
=> revert(ci): use Python 3.10

.github/workflows/publish.yml
We are using coatl-dev/workflows/.github/workflows/pypi-upload.yml@v4.0.1
With GitHub dropping python2.7 from `ubuntu-20.04` we have to rely on the `coatl-dev/action-pypi-upload` action
=> ci(publish): use coatl-dev/action-pypi-upload@v0.2.0

.github/workflows/main.yml, .github/workflows/publish.yml
We are using the full tag version for reusable workflows and the pypi upload action.
The team at coatl-dev has created tags with just the major version, so we will take advantage of them.
=> ci: use major version tags for workflows and actions

src/com/inductiveautomation/ignition/common/tags/model/__init__.py
We get `ImportError: cannot import name BrowseFilter` when we try to import `system.tag` on an interactive session.
Issue Number: #222
This issue is resolved.
Fixes: #222
=> fix(system): fix system.tag import error

src/system/db.py
All NamedQuery functions only allow `*args`
Allow `*args` and `**kwargs`
=> refactor(system): add kwargs to named query functions

src/system/db.py
this method can return a PyDataSet or any other object
depending on the type of query
=> refactor(system): change db.runNamedQuery return type to Any

.github/workflows/ci.yml, .github/workflows/pip-compile-upgrade.yml, .github/workflows/pr-build.yml, .github/workflows/pre-commit-autoupdate.yml, .github/workflows/publish.yml, .pylintrc, src/com/inductiveautomation/ignition/common/script/__init__.py, src/org/python/core/__init__.py, tox.ini
We import `PyStringMap` from `copy` in both `src.com.inductiveautomation.ignition.common.script` and use Python 3.11 for running CI.
We import from `org.python.core` and use `coatl-dev/workflows@v3` and Python 3.12 for CI.
use coatl-dev/workflows@v3
replace Python 3.11 with 3.12
=> refactor(ia): import PyStringMap from org.python.core

.pre-commit-config.yaml
when installing pylint in isolation, e.g. via pipx, it flags setup.py
with E0401 because it cannot find setuptools in that environment
=> build(pre-commit): limit pylint to run against the src directory
