ignition-devs/ignition-api-8.1

.github/workflows/pypi_upload.yml, setup.cfg
- update `pypi_upload` workflow
- update `setup.cfg` to include `CHANGELOG.md` in future releases
=> ci: fix packaging issues

README.md
=> docs: replace old project name

.github/dependabot.yml, .github/workflows/pypi_upload.yml
add `dependabot.yml`
update `pypi_upload.yml` so it doesn't run in forks
=> ci: maintenance

.github/workflows/pypi_upload.yml
=> revert(ci): remove condition from job

.pylintrc, src/com/inductiveautomation/ignition/common/model/__init__.py
=> refactor: improve Version comparison logic

README.md
=> docs: use pepy.tech for counting downloads

README.md
=> docs(readme): add link to org CONTRIBUTING.md

src/system/perspective/__init__.py
support 21 CFR Part 11 electronic signature requirements
There was no function.
=> feat(system): add perspective.authenticationChallenge

src/com/inductiveautomation/ignition/common/browsing/__init__.py
Adds fields to the Results class and updates getters and setters.
=> feat(system): add fields to Results class

.github/workflows/ci.yml
With this update `mypy` will run in "Python 2 mode" by passing the `--py2` argument.
=> ci: use Python 2 mode for mypy

src/com/inductiveautomation/ignition/common/__init__.py, src/com/inductiveautomation/ignition/common/script/builtin/__init__.py, src/com/inductiveautomation/ignition/common/user/__init__.py, src/com/inductiveautomation/ignition/common/user/schedule/__init__.py, src/com/inductiveautomation/ignition/common/util/__init__.py, src/javax/swing/__init__.py, src/org/apache/commons/lang3/builder/__init__.py
`java.lang.String` is not being used in all modules.
`from java.lang import String`
=> refactor: use java.lang.String

src/com/inductiveautomation/factorypmi/application/__init__.py, src/org/python/core/__init__.py, src/org/slf4j/__init__.py
We're still using `str` as a return type in some functions, and we're missing all classes in `__all__` for `org.python.core`
Use java.lang.String where applicable, add classes to `__all__`.
=> refactor: improve code quality

src/com/inductiveautomation/ignition/common/model/values/__init__.py, src/com/inductiveautomation/ignition/common/script/builtin/__init__.py, src/java/lang/__init__.py, src/javax/swing/text/__init__.py, src/system/gui.py
=> feat: improve type hints

src/system/perspective/__init__.py, src/system/tag.py
Add new functions under `perspective` and `tag` modules.
[New in Ignition 8.1.19](https://docs.inductiveautomation.com/display/DOC81/New+in+this+Version#NewinthisVersion-Newin8.1.19)
=> feat(system): add new perspective and tag functions

src/com/inductiveautomation/ignition/common/model/values/__init__.py
BasicQualifiedValue's properties are "protected"
Issue Number: #47
BasicQualifiedValue's properties are now accessible.
=> fix(ia): make class' properties accessible

src/com/inductiveautomation/ignition/common/browsing/__init__.py, src/com/inductiveautomation/ignition/common/functional/__init__.py, src/com/inductiveautomation/ignition/common/messages/__init__.py, src/com/inductiveautomation/ignition/common/opc/__init__.py, src/com/inductiveautomation/ignition/common/script/builtin/__init__.py, src/com/inductiveautomation/ignition/common/user/schedule/__init__.py, src/java/util/__init__.py, src/java/util/function/__init__.py, src/system/tag.py
The new `system.tag.query` has the wrong return type, and arg names.
Return type is now correct, and argument names.
https://forum.inductiveautomation.com/t/possible-error-in-system-tag-query-documentation-8-1-19/62496/6?u=thecesrom.git
=> fix(system): fix args and return type of tag.query

src/com/inductiveautomation/ignition/common/__init__.py, src/com/inductiveautomation/ignition/common/script/builtin/__init__.py, src/system/dataset.py
See issue.
Issue Number: #51
All classes implementing `Dataset` will be accepted.
=> fix(system): accept instances of Dataset

src/com/inductiveautomation/ignition/common/script/builtin/__init__.py
These classes have no fields.
Fields have been added.
=> feat(ia): add fields to SprocCall, SprocArg, and SProcArgKey

src/java/net/__init__.py, src/java/nio/channels/__init__.py
java.net.Socket functions are missing type annotation
Issue Number: #55
Type annotations are present
=> feat(java): add type hints to Socket functions

src/system/tag.py
`tags` is of type `Any`
Change from `Any` to `List[Dict[String, Any]`.
=> refactor(system): change type for `tags` argument

src/com/inductiveautomation/ignition/common/script/adapters/__init__.py, src/com/inductiveautomation/ignition/common/user/schedule/__init__.py, src/javax/swing/__init__.py
Unused imports have been removed.
=> perf: remove unused imports

src/system/db.py, src/system/serial.py
=> style(system): remove white-space

src/java/io/__init__.py, src/java/lang/__init__.py, src/java/net/__init__.py, src/java/nio/__init__.py, src/java/nio/channels/__init__.py, src/java/nio/file/__init__.py
Some methods were missing type hints.
Add type hints to some Java methods.
Add supporting classes, and packages.
=> feat(java): improve typing

.github/workflows/ci.yml, requirements.ci.txt, requirements.dev.txt
There is no requirements file.
Add requirements file for CI and Development.
With `mypy` v0.980 dropping Python 2 support, we must lock our dependency on `mypy` to anything less than 0.980.
=> ci: add requirements file for CI

src/com/inductiveautomation/ignition/common/opc/__init__.py
We don't have `com.inductiveautomation.ignition.common.BrowseElement`.
`BrowseElement` and its subclass have been implemented.
=> feat(ia): implement ignition.common.BrowseElement

src/com/inductiveautomation/ignition/common/__init__.py, src/com/inductiveautomation/ignition/common/gson/__init__.py, src/com/inductiveautomation/ignition/common/gson/reflect/__init__.py, src/com/inductiveautomation/ignition/common/gson/stream/__init__.py, src/com/inductiveautomation/ignition/common/jsonschema/__init__.py, src/com/inductiveautomation/perspective/common/__init__.py, src/java/io/__init__.py, src/java/lang/__init__.py, src/java/util/function/__init__.py, src/java/util/regex/__init__.py
There is no `PerspectiveModule` class, nor `perspective` package under `com.inductiveautomation`.
Issue Number: #67 
`PerspectiveModule` and supporting packages and classes have been added.
=> feat(ia): add PerspectiveModule class

.pylintrc, src/com/inductiveautomation/ignition/common/__init__.py, src/com/inductiveautomation/ignition/common/document/__init__.py, src/com/inductiveautomation/ignition/common/i18n/__init__.py, src/com/inductiveautomation/ignition/common/sqltags/model/types/__init__.py, src/java/lang/__init__.py, src/java/util/__init__.py, src/java/util/function/__init__.py, src/org/json/__init__.py, src/org/python/core/__init__.py
We don't have the `TypeUtilities` under `com.inductiveautomation.ignition.common`
Issue Number: #66
This PR adds the `TypeUtilities` class, and also adds and updates supporting classes and packages.
=> feat(ia): add TypeUtilities under ignition.common

src/system/print.py, src/system/tag.py, src/system/util.py
We don't have all `system.*` constants.
Issue Number: #75
This PR adds missing constants to the following modules: `print`, `tag`, and `util`.
=> feat(system): add missing `system` constants

src/system/dataset.py, src/system/db.py, src/system/opc.py, src/system/print.py, src/system/serial.py, src/system/util.py
Closes: #76
We have class aliases which pollute the stubs files.
Issue Number: #76
Class aliases have been removed.
Small caveat; a type alias had to be created for `system.opc.browseServer` as the type comment would be greater that 72 characters.
=> refactor(system): remove class aliases

src/com/inductiveautomation/ignition/common/model/__init__.py, src/java/nio/file/__init__.py
Issue Number: #81
Add `com.inductiveautomation.ignition.common.model.ApplicationScope`
=> feat(ia): add ApplicationScope class

src/dev/thecesrom/utils/decorators.py, src/java/awt/__init__.py, src/java/lang/__init__.py, src/java/org/jdesktop/core/animation/timing/__init__.py, src/java/util/__init__.py, src/javax/swing/__init__.py, src/javax/swing/event/__init__.py, src/javax/swing/plaf/__init__.py
When running `mypy --strict` we get the following errors for `java`:
```sh
$ mypy --strict src/java
src/dev/thecesrom/utils/decorators.py:5: error: Function is missing a type annotation
src/java/lang/__init__.py:106: error: Function is missing a return type annotation
src/java/lang/__init__.py:106: note: Use "-> None" if function does not return a value
src/java/lang/__init__.py:109: error: Function is missing a return type annotation
src/java/lang/__init__.py:109: note: Use "-> None" if function does not return a value
src/java/lang/__init__.py:196: error: Function is missing a type annotation
src/java/lang/__init__.py:237: error: Function is missing a type annotation …
```
=> feat(java): add type hints to all java and javax classes and methods

src/system/net.py
`smtp` is mandatory.
Issue Number: #84
`smtp` is optional.
A new internal function `_sendEmail` has been added.
=> fix(system): set smtp keyword argument as optional

.pylintrc, src/java/io/__init__.py, src/java/nio/channels/__init__.py, src/java/nio/charset/__init__.py, src/java/nio/file/__init__.py, src/java/nio/file/attribute/__init__.py, src/java/security/__init__.py, src/java/time/__init__.py, src/java/time/format/__init__.py, src/java/time/temporal/__init__.py, src/java/util/__init__.py, src/java/util/concurrent/__init__.py, src/java/util/function/__init__.py, src/java/util/stream/__init__.py, src/javax/security/auth/__init__.py
We don't have `Files` and `Paths` under `java.nio.file`.
Issue Number: #88
This PR adds those classes and dependencies.
Closes: #88
=> feat(java): add java.nio Files and Paths

src/java/math/__init__.py, src/java/text/__init__.py, src/java/util/__init__.py
`java.text.SimpleDateFormat` does not exist in our API.
This PR adds `java.text.SimpleDateFormat` as well as supporting classes.
=> feat(java): add java.text.SimpleDateFormat class

src/com/inductiveautomation/ignition/common/i18n/__init__.py
The `LocaleUtils` class does not exist in our API.
This PR adds `LocaleUtils` class.
=> feat(ia): add LocaleUtils

.github/workflows/ci.yml
=> ci(github): set Python version via env variable

src/system/util.py
Add `system.util.getModules` in preparation for `v8.1.21`.
=> feat(system): add util.getModules function

src/com/inductiveautomation/ignition/alarming/common/rosters/__init__.py, src/com/inductiveautomation/ignition/client/util/gui/scheduling/__init__.py, src/com/inductiveautomation/ignition/common/user/schedule/__init__.py, src/com/palantir/ptoss/cinch/core/__init__.py, src/system/roster.py
Add new `system.roster` functions `getRoster` and `getRosterNames`, and supporting classes.
=> feat(system): add new roster functions from 8.1.21

.github/workflows/ci.yml
We run `tox` as a module.
Run `tox` as an executable.
=> ci(github): run tox as executable

src/com/inductiveautomation/ignition/common/__init__.py, src/com/inductiveautomation/ignition/common/tags/model/__init__.py, src/com/inductiveautomation/ignition/common/tags/paths/parser/__init__.py
`TagPathParser` class does not exist.
Issue Number: #104 
We've introduced `TagPathParser` and `TagPath` classes, and modified `Path`  to be a proper Interface.
Closes: #104
=> feat(ia): add TagPathParser class

src/com/inductiveautomation/ignition/common/__init__.py, src/com/inductiveautomation/ignition/common/gson/__init__.py, src/com/inductiveautomation/ignition/common/tags/model/__init__.py, src/com/inductiveautomation/ignition/common/tags/paths/__init__.py, src/com/inductiveautomation/ignition/common/tags/paths/parser/__init__.py, src/com/inductiveautomation/ignition/common/tags/tagpaths/__init__.py
Issue Number: #106
Add classes implementing `TagPath`.
=> feat(ia): add classes implementing TagPath

setup.cfg, tox.ini
Enable [`isolated_build`](https://tox.wiki/en/latest/config.html#conf-isolated_build).
=> test(tox): update tox configuration

.pylintrc
```sh
$ pylint --version                       
pylint 2.15.3
astroid 2.12.10
Python 3.10.7 (main, Oct  8 2022, 12:22:33) [Clang 12.0.0 (clang-1200.0.32.29)]
$ pylint --generate-rcfile > .pylintrc
```
=> chore: update pylint configuration

tox.ini
=> test(tox): reorder envs

.pylintrc, src/com/inductiveautomation/ignition/common/script/abc/__init__.py, src/com/inductiveautomation/ignition/common/script/builtin/__init__.py, src/java/util/__init__.py, src/java/util/function/__init__.py, src/org/python/core/__init__.py, tox.ini
Module `abc` from package `com.inductiveautomation.common.script` do not have type comments.
Implement type comments.
Add supporting classes.
=> refactor(ia): add type hint to common.script.abc classes

src/com/inductiveautomation/factorypmi/application/script/__init__.py, src/com/inductiveautomation/factorypmi/application/script/builtin/__init__.py, src/com/inductiveautomation/ignition/common/script/builtin/__init__.py, src/com/inductiveautomation/ignition/common/tags/tagpaths/__init__.py, src/java/awt/__init__.py, src/java/awt/event/__init__.py, src/java/awt/geom/__init__.py, src/java/awt/print/__init__.py, src/org/python/core/__init__.py, src/system/gui.py, src/system/print.py, src/system/roster.py
`DatasetUtilities` and `WindowUtilities` classes are missing type hints.
Type hints have been implemented, and supporting classes have been added.
=> refactor(ia): add type hints to DatasetUtilities and WindowUtilities

src/com/inductiveautomation/ignition/common/alarming/query/__init__.py, src/com/inductiveautomation/ignition/common/script/builtin/__init__.py, src/java/awt/event/__init__.py
=> refactor: improve type hints

src/com/inductiveautomation/ignition/common/script/abc/__init__.py, src/com/inductiveautomation/ignition/common/script/adapters/__init__.py, src/org/python/core/__init__.py
Issue Number: #118
Closes: #118
=> fix: change type hints on __iter__ methods

.github/workflows/ci.yml, tox.ini
We are `pip`-installing `tox-gh` to run `tox` envs.
We will not depend on `tox-gh`
remove tox-gh configuration from tox.ini
rework tox envs
=> ci: drop tox-gh

requirements.ci.txt, tox.ini
`py27` is being executed when using Python 3.10.
Test environments have been rolled back to `install`, `lint`, and `typecheck`.
=> test(tox): revert envlist changes

src/org/apache/commons/math3/exception/__init__.py
Signature is not compatible with __new__
=> refactor(org): update MathIllegalArgumentException __init__ signature

src/dev/thecesrom/utils/decorators.py, src/java/lang/__init__.py, src/java/nio/file/__init__.py, src/java/util/__init__.py, src/java/util/stream/__init__.py, src/org/apache/commons/math3/exception/__init__.py, src/org/apache/commons/math3/exception/util/__init__.py, src/org/python/core/__init__.py, tox.ini
add ExceptionContext class
increase mypy strictness
=> chore: improve type hints

.pre-commit-config.yaml, README.md
We are using `commitizen` v2.37.0
Bump `commitizen` to v2.37.1.
Update `pre-commit` badge.
=> Build/deps/bump commmitizen v2.37.1

tox.ini
When we modify source files we manually generate the stubs.
With this additional environment we will be able to generate ignition-api/stubs by running `tox -e stubgen` from the Terminal.
=> chore(tox): add stubgen environment

.pre-commit-config.yaml
=> build(deps): bump isort 5.11.0 → 5.11.1

.pre-commit-config.yaml
We use isort 5.11.1
We will use isort 5.11.2
=> build(deps): bump isort 5.11.2

.github/workflows/ci.yml, .pylintrc, requirements.ci.txt, tox.ini
We use Python 3.10 for running linting and static checks.
We will switch to Python 3.11.
=> ci: use Python 3.11

.github/workflows/ci.yml
We use a matrix strategy for running tox.
We will use a single Python version.
=> refactor(ci): simplify ci workflow

.github/dependabot.yml, .github/workflows/ci.yml, .github/workflows/pypi_upload.yml, .sourcery.yaml, tox.ini
We are not caching dependencies on our workflows.
We will cache `pip` and `tox` on our workflows.
apply style to all YAML files
update pre-commit step in tox.ini
=> ci: cache workflows to improve performance

.github/workflows/ci.yml, tox.ini
=> ci: cache pre-commit

.github/workflows/ci.yml, tox.ini
update lint tox env
use snake_case for tox option names
=> ci: use default location for caching pre-commit

.github/workflows/ci.yml
=> ci: update cache keys

.github/workflows/publish.yml
=> ci: pass secrets onto reusable workflow

.github/workflows/main.yml, .github/workflows/publish.yml
We're using v0.0.4
We will use v0.1.0
=> ci: use thecesrom/workflows v0.1.0

src/com/inductiveautomation/ignition/common/__init__.py, src/java/util/__init__.py
None.
We will add [`java.util.Arrays`]; useful when [comparing two Datasets][link2].
[`java.util.Arrays`]: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Arrays.html
[link2]: https://forum.inductiveautomation.com/t/comparing-two-datasets-values-and-using-those-to-determine-difference/23676/12?u=thecesrom.git
=> feat(java): add util.Arrays static class

src/java/awt/__init__.py, src/java/awt/geom/__init__.py, src/javax/swing/__init__.py
We will add `java.awt.GridLayout` and `javax.swing.JPasswordField`.
add supporting classes
Closes: #168, #169
=> feat(java): add GridLayout and JPasswordField

.cz.yaml, setup.cfg, src/system/__version__.py, src/system/util.py
this will allow us to bump the version with commitizen
=> refactor(system): change how we extract the version

src/javax/swing/__init__.py, src/javax/swing/text/__init__.py
We don't provide `getText()`
We will add `getText()` with a `DeprecationWarning`.
warn about deprecation
=> feat(javax): add JPasswordField getText

src/javax/swing/__init__.py
=> fix(javax): add return type to JPasswordField.getPassword

.github/workflows/main.yml, .github/workflows/publish.yml
=> ci: use coatl-dev/workflows v1.2.1

.github/workflows/main.yml, .github/workflows/publish.yml
=> ci: use coatl-dev/workflows@v2.2.0

.pre-commit-config.yaml, src/system/iec61850.py
We do not have the `iec61850` module.
This will add that module.
Closes: #180
=> feat(system): add iec61850 module

.pre-commit-config.yaml, src/com/inductiveautomation/factorypmi/application/script/builtin/__init__.py, src/com/inductiveautomation/ignition/common/model/__init__.py, src/com/inductiveautomation/ignition/common/model/values/__init__.py, src/java/io/__init__.py, src/java/lang/__init__.py, src/java/util/__init__.py, src/javax/swing/__init__.py, src/org/apache/commons/math3/exception/__init__.py, src/system/db.py, src/system/dnp3.py, src/system/gui.py, src/system/net.py, src/system/opcua.py, src/system/perspective/__init__.py, src/system/user.py, src/system/util.py, src/system/vision.py, tox.ini
We don't use `docformatter`
We will use `docformatter`.
update style tox env
=> build(deps): add docformatter

src/dev/thecesrom/helper/types.py, src/system/dataset.py
We are using `BasicDataset` for args and return types on `system.dataset`.
We will use the parent class `Dataset` for bot args and return types.
BREAKING CHANGE: use Dataset instead of BasicDataset on dataset module
add AnyNum type
use AnyNum for ColType
=> refactor(system): replace BasicDataset with Dataset

.pre-commit-config.yaml
update:
- black 23.1.0 → 23.3.0
=> build(deps): bump black to 23.3.0

src/com/inductiveautomation/opccom/hda/__init__.py, src/system/opchda.py
add opccom.hda subpackage under com.inductiveautomation fix types and return types
=> refactor(system): return AttributeInfo and RadResult

src/system/alarm.py, src/system/dataset.py, src/system/date.py, src/system/opcua.py, src/system/report.py, src/system/roster.py, src/system/secsgem.py, src/system/security.py, src/system/serial.py, src/system/tag.py, src/system/util.py
=> refactor(system): fix types and return types

src/system/perspective/__init__.py, src/system/print.py
sneak in perspective which was meant to be included in #189
=> feat(system): add missing print functions from 8.1.22

.flake8, .pylintrc, src/com/inductiveautomation/ignition/common/xmlserialization/__init__.py, src/com/inductiveautomation/ignition/common/xmlserialization/serialization/__init__.py, src/org/apache/log4j/spi/__init__.py, src/org/python/core/__init__.py
flake8, pylint: increase max-line-length to 120
=> style: use import from instead of importing the module

src/com/inductiveautomation/ignition/common/__init__.py
See issue
Issue Number: #192
It's all good now.
* Not necessarily
=> fix(ia): solve cyclic import error

src/com/inductiveautomation/ignition/common/sqltags/history/__init__.py, src/java/util/__init__.py, src/system/util.py
We don't have `system.utils.globals`
We will have `system.utils.globals`
=> feat(system): add system.utils.globals dictionary

src/com/inductiveautomation/ignition/common/tags/model/__init__.py, src/com/inductiveautomation/ignition/common/tags/paths/__init__.py
`TagPath` is not an interface.
`TagPath` is now an interface.
=> refactor(ia): set TagPath as an interface

.sourcery.yaml, src/system/util.py
sourcery: disable avoid-builtin-shadow
=> chore(system): add globals to __all__

README.md, src/system/__version__.py
=> chore(release): prepare for v8.1.27

.pre-commit-config.yaml, setup.py
update:
- docformatter: v1.5.1 → v1.6.3
- commitizen: v2.42.1 → 3.1.0
=> build(deps): bump dependencies

.github/workflows/main.yml, .github/workflows/publish.yml
=> ci: use coatl-dev/workflows@v3.0.0

tox.ini
=> style(tox): format tox with tox-ini-fmt

.pre-commit-config.yaml
update:
- commitizen: 3.2.1 → 3.2.2
=> build(deps): bump commitizen to 3.2.2

.pre-commit-config.yaml
=> build(deps): bump docformatter to v1.7.1

.github/workflows/main.yml, .github/workflows/publish.yml
=> ci: use coatl.dev workflows@4.0.1

tox.ini
<https://tox.wiki/en/latest/faq.html#testing-end-of-life-python-versions>
=> test(tox): require virtualenv<20.22.0

src/system/project.py
Add system.project.requestScan
=> feat(system): add system.project.requestScan

src/com/inductiveautomation/ignition/common/i18n/keyboard/__init__.py, src/system/vision.py
=> feat(system): add system.vision.getKeyboardLayouts

.github/workflows/main.yml, .github/workflows/publish.yml
bump:
-coatl-dev/action-pypi-upload: v0.2.0 to v1.0.0
=> ci: use tox-docker workflow

.github/workflows/main.yml
We are using `coatl-dev/workflows@v5.1.1`
We will use `coatl-dev/workflows@v5.1.2`
=> ci: use coatl-dev/workflows@5.1.2

src/system/__version__.py
<https://support.inductiveautomation.com/hc/en-us/articles/17614629296269-8-1-29-LTS-Pulled-from-Downloads-8-1-30-Emergency-Release->
=> fix(system): prepare for 8.1.30

.pre-commit-config.yaml, .pylintrc
update pylint configuration file
=> build(deps): bump commitizen to 3.6.0

.pre-commit-config.yaml, src/java/lang/__init__.py, src/java/math/__init__.py, src/org/bson/__init__.py, src/org/bson/codecs/__init__.py, src/org/bson/codecs/configuration/__init__.py, src/org/bson/types/__init__.py, src/system/mongodb/__init__.py, src/system/mongodb/types.py
=> feat(system): add mongodb module

.github/workflows/main.yml, src/system/bacnet/__init__.py, tox.ini
Issue Number: #229, #230
Add new features from Ignition 8.1.32
use Python 3.11 for running our tools
Closes: #229, #230
=> feat(system): add Ignition 8.1.32 new features

.pre-commit-config.yaml
We are running commitizen as a pre-commit hook
We are removing commitizen pre-commit hook.
=> build(deps): remove commitizen

.github/workflows/pip-compile-upgrade.yml, .github/workflows/pre-commit-autoupdate.yml
switch from coatl-dev/actions to coatl-dev/workflows
=> ci: use pre-commit-autoupdate and pip-compile-upgrade workflows

src/com/inductiveautomation/ignition/common/model/__init__.py, tests/test_system.py, tox.ini
When import `system.gui` or `system.nav` we get the following error message: `ImportError: cannot import name FunctionFactory` due to a cyclical import.
This has been fixed.
add tests
=> fix(system): fix issue when importing system.gui and system.nav

.github/workflows/pr-build.yml, tests/test_system.py
We have a function for each module we are testing.
We will have one single test using pytest.mark.parametrize passing a list of all modules
=> test: parametrize tests

src/com/inductiveautomation/ignition/client/launch/__init__.py, src/com/inductiveautomation/ignition/client/util/gui/scheduling/__init__.py, src/com/inductiveautomation/ignition/common/__init__.py, src/com/inductiveautomation/ignition/common/alarming/__init__.py, src/com/inductiveautomation/ignition/common/browsing/__init__.py, src/com/inductiveautomation/ignition/common/gui/progress/__init__.py, src/com/inductiveautomation/ignition/common/licensing/__init__.py, src/com/inductiveautomation/ignition/common/model/values/__init__.py, src/com/inductiveautomation/ignition/common/modules/__init__.py, src/com/inductiveautomation/ignition/common/project/resource/__init__.py, src/com/inductiveautomation/ignition/common/script/builtin/http/__init__.py, src/com/inductiveautomation/ignition/common/sqltags/history/annotations/__init__.py, src/com/inductiveautomation/ignition/common/sqltags/model/types/__init__.py, src/com/inductiveautomation/ignition/common/tags/config/types/__init__.py, src/com/inductiveautomation/ignition/common/user/schedule/__init__.py, src/com/inductiveautomation/ignition/common/xmlserialization/serialization/__init__.py, src/java/lang/__init__.py, src/java/util/__init__.py, src/javax/swing/__init__.py, src/org/apache/log4j/__init__.py, src/org/bson/__init__.py, src/org/bson/types/__init__.py, src/org/python/core/__init__.py
=> refactor: update default boolean returns

README.md, src/system/__version__.py
https://support.inductiveautomation.com/hc/en-us/articles/27020649332877-Regression-for-8-1-40
=> fix: fix regression found in 8.1.40

src/com/inductiveautomation/ignition/common/alarming/query/__init__.py, src/java/util/__init__.py
`AlarmQueryResultImpl` inherits from `AlarmQueryResult`.
Issue Number: #283
`AlarmQueryResultImpl` inherits from `AlarmQueryResult` and `java.util.ArrayList`
=> fix(ia): inherit from java.util.ArrayList
